# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Integration Testing
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  skopeo-encrypt-decrypt:
    runs-on: ubuntu-20.04
    needs: build-pilot    
    steps:
    
      - id: download
        uses: actions/download-artifact@v3
        with:
          name: pilot_jar

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64

      - name: get jar name
        run: | 
          export JAR_NAME=$(find . -name pilot*.jar)
          echo "JAR_NAME=${JAR_NAME}" >> $GITHUB_ENV

      - name: Run pilot
        run: nohup java -jar ${JAR_NAME} &

      - name: check for pilot running
        run: ps -ef |grep pilot

      - name: Install skopeo
        run: |
          sudo apt-get -y update && sudo apt-get -y install skopeo

      - name: Pull busybox
        run: skopeo copy docker://busybox:latest oci:busybox

      - name:
        uses: "finnp/create-file-action@master"
          env:
            FILE_NAME: "ocicrypt.conf"
            FILE_BASE64: "Z3JwYyI6ICJsb2NhbGhvc3Q6NTAwNTEiCiAgICAgICAgfQogICAgfQp9Cg=="

      - name: Encrypt image using test key
        run: |
          OCICRYPT_KEYPROVIDER_CONFIG=ocicrypt.conf skopeo copy --encryption-key provider:pilot:testkey oci:busybox oci:encrypted

      - name: Decrypt image using tesst key
        run: |
          OCICRYPT_KEYPROVIDER_CONFIG=ocicrypt.conf skopeo copy --decryption-key provider:pilot:testkey oci:encrypted oci:decrypted
