# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-pilot:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: set-vars
        run: |
          # Find the built jar in the target/ directory
          export JAR_PATH=$(find target/ -name pilot*.jar)
          # Make JAR_PATH available to next step
          echo "JAR_PATH=${JAR_PATH}" >> $GITHUB_ENV

      - name: Upload pilot.jar
        uses: actions/upload-artifact@v3
        with:
          name: pilot
          path: ${{ env.JAR_PATH }}

  run-pilot:
    runs-on: ubuntu-20.04
    needs: build-pilot    
    steps:
    
      - id: download
        uses: actions/download-artifact@v3
        with:
          name: pilot

      - name: check what's in this directory
        run: ls -al

      - name: Run pilot
        run: nohup java -jar ${{steps.download.outputs.download-path}} &

      - name: Finish
        run: echo "done!"
